cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DAnimationd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DCored.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DExtrasd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DInputd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DLogicd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickAnimationd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickExtrasd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickInputd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickRenderd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickScene2Dd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DRenderd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Bluetoothd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Concurrentd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Cored.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5DBusd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Designerd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5DesignerComponentsd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Gamepadd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Guid.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Helpd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Locationd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Multimediad.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5MultimediaQuickd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5MultimediaWidgetsd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Networkd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Nfcd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5OpenGLd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Positioningd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5PositioningQuickd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5PrintSupportd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Qmld.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Quickd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickControls2d.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickParticlesd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickShapesd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickTemplates2d.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickTestd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickWidgetsd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5RemoteObjectsd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Scxmld.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Sensorsd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5SerialBusd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5SerialPortd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Sqld.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Svgd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Testd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5TextToSpeechd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WebChanneld.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WebSocketsd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WebViewd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Widgetsd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WinExtrasd.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Xmld.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5XmlPatternsd.dll ..\game\bin\tools\dxfm
