cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DAnimation.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DCore.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DExtras.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DInput.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DLogic.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuick.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickAnimation.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickExtras.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickInput.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickRender.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DQuickScene2D.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt53DRender.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Bluetooth.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Concurrent.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Core.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5DBus.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Designer.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5DesignerComponents.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Gamepad.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Gui.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Help.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Location.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Multimedia.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5MultimediaQuick.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5MultimediaWidgets.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Network.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Nfc.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5OpenGL.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Positioning.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5PositioningQuick.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5PrintSupport.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Qml.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Quick.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickControls2.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickParticles.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickShapes.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickTemplates2.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickTest.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5QuickWidgets.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5RemoteObjects.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Scxml.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Sensors.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5SerialBus.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5SerialPort.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Sql.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Svg.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Test.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5TextToSpeech.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WebChannel.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WebSockets.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WebView.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Widgets.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5WinExtras.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5Xml.dll ..\game\bin\tools\dxfm
cp tools\directorscut\thirdparty\lgpl\qt\bin\Qt5XmlPatterns.dll ..\game\bin\tools\dxfm
